runners:
  x86_64-runner:
    cpu: [64, 72, 96, 128, 192]
    ram: [128, 144, 192, 256, 384, 512]
    family: ["c5", "c6", "c7", "c8", "m5", "m6", "m7", "m8", "r6", "r7", "r8", "g4", "g5"]
    spot: price-capacity-optimized
    disk: large
    image: ubuntu24-stepsecurity-x64
    ssh: false

  arm64-runner:
    cpu: [64, 72, 96, 128, 192]
    ram: [128, 144, 192, 256, 384, 512]
    family: ["c5", "c6", "c7", "c8", "m5", "m6", "m7", "m8", "r6", "r7", "r8", "g4", "g5"]
    spot: price-capacity-optimized
    disk: large
    image: ubuntu24-stepsecurity-arm64
    ssh: false